name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  test_async:
    runs-on: ubuntu-latest
    steps:
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: node_modules/
        key: v1-npm-deps-${{ hashFiles('**/package-lock.json') }}
        restore-keys: v1-npm-deps-
  install:
    runs-on: ubuntu-latest
    steps:
      - run: npm install

  lint:
    runs-on: ubuntu-latest
    needs: [install]
    steps:
      - run: npm run lint

  test:
    runs-on: ubuntu-latest
    needs: [install, lint]
    steps:
      - run: npm run test

  deploy_ab:
    runs-on: ubuntu-latest
    needs: [test]
    steps:
      - run: |
          apt-get update -qy
          apt-get install -y ruby-dev
          gem install dpl
          dpl --provider=heroku --app=$HEROKU_APP_NAME --api-key=$HEROKU_API_KEY
          
